import test from "node:test";
import assert from "node:assert/strict";
import { STEP8G_V8005_RUNTIME_DESCRIPTOR } from "../data/generated/step8g/v8005-runtime-descriptor.mjs";
import { STEP8G_V8005_EXPECTED_BODY_BATCH_COUNT, STEP8G_V8005_EXPECTED_RECIPE_COUNT, STEP8G_V8005_EXPECTED_ROUTE_COUNT, expectedStep8GV8005BodyBatchIds, expectedStep8GV8005RouteBatchIds, materializeStep8GV8005IncomingBodyBatch, publicStep8GV8005RouteBatch, publicStep8GV8005Summary } from "../src/server/step8g-v8005-live-runtime.mjs";
import { hydrateStep8GV8005ProtectedRecipesBounded } from "../src/server/step8g-v8005-hydration-runtime.mjs";
import { onRequestGet as getV8005 } from "../functions/api/step8g/v8005.js";

const ORIGIN="https://culinary-recommender-app.pages.dev";
test("v8005 freezes 109 Bosse/Watanna rows and 2464 composed routes on two shards",()=>{const summary=publicStep8GV8005Summary();assert.equal(summary.recipeCount,STEP8G_V8005_EXPECTED_RECIPE_COUNT);assert.equal(summary.cumulativeRecipeCount,STEP8G_V8005_EXPECTED_ROUTE_COUNT);assert.equal(summary.bodyBatchCount,STEP8G_V8005_EXPECTED_BODY_BATCH_COUNT);assert.equal(summary.newRouteBatchCount,12);assert.equal(summary.maxRowsPerBatch,10);assert.equal(summary.maxProtectedD1Subqueries,16);assert.deepEqual(STEP8G_V8005_RUNTIME_DESCRIPTOR.bodyShardRows,[61,48]);assert.equal(expectedStep8GV8005BodyBatchIds().length,12);assert.equal(expectedStep8GV8005RouteBatchIds().length,12);assert.equal(summary.publicRuntimeActivationAuthorized,false);assert.equal(summary.recommendationAdmissionAuthorized,false);assert.equal(summary.billingExpansionAuthorized,false);assert.equal(summary.thirdShardAuthorized,false);assert.equal(summary.culturalAuthenticityAuthorityImported,false);});
test("v8005 route batches freeze exact hashes and never exceed 10 rows",()=>{for(const id of expectedStep8GV8005RouteBatchIds()){const batch=publicStep8GV8005RouteBatch(id);assert.ok(batch);assert.ok(batch.rowCount>=1&&batch.rowCount<=10);assert.match(batch.expectedSha256,/^[0-9a-f]{64}$/);}assert.equal(publicStep8GV8005RouteBatch("route-v8005-s00-b999999"),null);});
test("unknown v8005 body batches fail closed before writes",async()=>{const result=await materializeStep8GV8005IncomingBodyBatch({batchId:"not-frozen",sourceEntries:[]});assert.equal(result.pass,false);assert.equal(result.reason,"UNKNOWN_BODY_BATCH_ID");});
test("v8005 unauthenticated API requests return 401 before protected shard access",async()=>{const explodingDb={prepare(){throw new Error("protected database should not be touched");}};const response=await getV8005({request:new Request(`${ORIGIN}/api/step8g/v8005?action=status`),env:{SESSION_SECRET:"0123456789abcdef0123456789abcdef",CULINARY_CONTROL_DB:explodingDb,CULINARY_RECIPE_SHARD_00_DB:explodingDb,CULINARY_RECIPE_SHARD_01_DB:explodingDb}});assert.equal(response.status,401);const body=await response.json();assert.equal(body.error,"UNAUTHORIZED");assert.equal(body.protectedDataReturned,false);assert.equal(body.shardQueries,0);});
test("v8005 hydration rejects empty and duplicate IDs before D1 access",async()=>{const explodingDb={prepare(){throw new Error("D1 should not be touched");}};const empty=await hydrateStep8GV8005ProtectedRecipesBounded(explodingDb,[explodingDb,explodingDb],[]);assert.equal(empty.pass,false);assert.equal(empty.reason,"RECIPE_IDS_REQUIRED");const dup=await hydrateStep8GV8005ProtectedRecipesBounded(explodingDb,[explodingDb,explodingDb],["x","x"]);assert.equal(dup.pass,false);assert.equal(dup.reason,"DUPLICATE_OR_EMPTY_RECIPE_ID");});
