import { chromium } from "playwright";
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
const errors = [];
page.on("pageerror", error => errors.push(error.message));
await page.goto(process.env.APP_URL || "http://127.0.0.1:4173", { waitUntil: "networkidle" });
await page.getByRole("heading", { name: "What should you cook?" }).waitFor();
await page.getByLabel("Dietary mode").selectOption("vegetarian");
await page.getByLabel("Protein emphasis").selectOption("4");
await page.getByRole("button", { name: /Build my plan/ }).click();
await page.getByRole("heading", { name: /meal.*built as a portfolio/ }).waitFor();
const cards = await page.locator(".recipe-card").count();
if (cards < 1) throw new Error("Expected at least one recipe card");
await page.getByRole("button", { name: "Groceries" }).click();
await page.getByRole("heading", { name: /One list/ }).waitFor();
await page.getByRole("button", { name: "Pantry" }).click();
await page.getByRole("heading", { name: /Pantry & cannot-find list/ }).waitFor();
if (errors.length) throw new Error(`Browser page errors: ${errors.join(" | ")}`);
await browser.close();
console.log("Browser smoke passed.");
